---

- name: configure and deploy the webservers and application code
  hosts: all
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: all
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - db
